In [26]:
import pandas as pd

In [27]:
cars = pd.read_csv("res/cars_missing_vals.csv")
cars

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [28]:
# rename column
cars = cars.rename(columns={'Unnamed: 0':'model'})
cars

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [29]:
# fill the null values with mean of the column
cars.qsec=cars.qsec.fillna(cars.qsec.mean())
cars

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2

In [30]:
# drop unwanted columns
cars = cars.drop(columns=['S.No'])
cars

,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2

In [ ]:
# find correlation matrix 
df = cars[['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']].corr()
df

In [ ]:
# change type of mpg to float
cars.mpg = cars.mpg.astype(float)

In [31]:
# change type of mpg to float
cars.mpg = cars.mpg.astype(float)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
mpg,1.000000,-0.852162,-0.847551,-0.776168,0.681172,-0.867659,0.360351,0.664039,0.599832,0.480285,-0.550925
cyl,-0.852162,1.000000,0.902033,0.832447,-0.699938,0.782496,-0.548775,-0.810812,-0.522607,-0.492687,0.526988
disp,-0.847551,0.902033,1.000000,0.790949,-0.710214,0.887980,-0.385207,-0.710416,-0.591227,-0.555569,0.394977
hp,-0.776168,0.832447,0.790949,1.000000,-0.448759,0.658748,-0.650674,-0.723097,-0.243204,-0.125704,0.749812
drat,0.681172,-0.699938,-0.710214,-0.448759,1.000000,-0.712441,0.120175,0.440278,0.712711,0.699610,-0.090790
wt,-0.867659,0.782496,0.887980,0.658748,-0.712441,1.000000,-0.130362,-0.554916,-0.692495,-0.583287,0.427606
qsec,0.360351,-0.548775,-0.385207,-0.650674,0.120175,-0.130362,1.000000,0.667873,-0.271763,-0.203784,-0.573987
vs,0.664039,-0.810812,-0.710416,-0.723097,0.440278,-0.554916,0.667873,1.000000,0.168345,0.206023,-0.569607
am,0.599832,-0.522607,-0.591227,-0.243204,0.712711,-0.692495,-0.271763,0.168345,1.000000,0.794059,0.057534
gear,0.480285,-0.492687,-0.555569,-0.125704,0.699610,-0.583287,-0.203784,0.206023,0.794059,1.000000,0.274073
carb,-0.550925,0.526988,0.394977,0.749812,-0.090790,0.427606,-0.573987,-0.569607,0.057534,0.274073,1.000000

In [32]:
# change type of mpg to float
cars.mpg = cars.mpg.astype(float)